============================================
''' This is the Start of Unit Testing... '''
============================================
''' TESTTING WITH the following... '''

''' Does the same as test below, but gives more details '''
# python3 -m doctest -v ./tests/file_name.txt
# python3 -m doctest -v ./tests/file_name.txt | tail -2

======================================
''' Importing TEMPLATE function''''
======================================
>>> add_integer = __import__('0-add_integer').add_integer

==============
SUCCESS CASES
==============

Category 1
==========
 ''' Expected output '''

>>> add_integer(2, 3)
5

>>> add_integer(2, 98)
100

>>> add_integer(2)
100

>>> add_integer(3.14)
101

>>> add_integer(3.14, 98)
101

>>> add_integer(98, 3.14)
101

>>> add_integer(1e100, 2)
10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815106

>>> add_integer(1, 2e100)
20000000000000000318057822195198360936721617127890562779562655115495677544340762121626939971713630209

>>> add_integer(-100, 2)
-98

>>> add_integer(1, -200)
-199

>>> add_integer(2e100)
20000000000000000318057822195198360936721617127890562779562655115495677544340762121626939971713630306

==========================
CASES THAT SHOULD NOT WORK
==========================

Category 2
==========
''' Expected Error Outputs '''

>>> add_integer('hola')
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(2, 'hello')
Traceback (most recent call last):
...
TypeError: b must be an integer

>>> add_integer(None, 2)
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(None)
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(2, None)
Traceback (most recent call last):
...
TypeError: b must be an integer

"""
